### ISSUE TITLE
explicit panic

### ISSUE THREAD

**Issue by hdashnow** [trgt-paper/tr-solve#3] opened 2023-09-28 04:41 UTC
I have quite a few sequences that generate this error, if you'd like more examples.

```
echo CCACACACACCAAACANCCCACACAACACACACACACCACACCACACAAACACAAACACACCACATCATGAACACACACATCACACACACACCACACACCCCACACACCCCACACACATCACACACACACACCACACACCCCACACAACACACAACACACACCACACACACCACACCACACACACACCACACCCCACAACACACACACACCACACTCCCCACTGAACACACACACATCACACACACCACACACCCCACACACACCACACACCCCACACAACACACACCACACACACACCACACCCCACAACACACACACATCACATCACACACACCACACCCCACACACACACACCACACCACACACACACCACACACCCCACACAACACATACACACATCACACACACCCCACACACCAACACACCACATCACACACACACCACATCACACACACACCAAACACCCCACACAACACACACACAACACAACACACACACAAACACACCACATCATACACACACCACACACCCCACACACCACACACACATCACACACACACCCCACACACCCCACACACCCCACACCACACTACACACACACCACACACCACACACAACACACACAACACAACACACACACCCCACACACAAACACCCCACACACCACACACACCACATCACACACACACACCACATCACACCCCACACAACACACACACCACACCACACACACACACCACACACCCCACACAACACACACCGCATCACACACACACCACACAACACACACACACCACACACACCACACACCCCACACAACACACAACACATCACACACACCACACACACCACACAACACACACATCACATACACACCACACACCACACACAACACATACACATCACACACACACCACACACCACACACAACACACACAACACAACACACACAACACACACCCCACACAACACACCACATCACACACACATCACACAACACACAACACAACACACACATCACACACCCCACACAACACACCACATCACACAAAACACATCACACACACAACACACACCCCACACAACACACACAACACAACACACACACCACACACCCCACACAACACACACAACACACCACACATATACATCACACACCACACACCCCACGCAACACACACACCACATCACACACACACCACACACCCCACACACACACGCATCACACCACACACACCACAGCCCCCACACAACACATACACACCACATCACACACACACCACACATCACATGTCATACACAGCACATACACCACACACACCACATAACATCACATGTCACACACACATCACATGACACATACACCACACACCCCATGCATCACACACACACCACACATCACATGTCATACATACTACATACACACAACACACACAACACATAACATCACATGTCACACACATCACATGACACACACCACACACTCCACACATCACATACACACTGCACATACACTACATCACACACCACACACCACACATCACATGTCACAAACACCACACAGCACACCCCACACCACACACATACACCACATACACAAATACCACACCACACACCACACATACACCACACCACACACACTTCACACACACCACACATCACATGTCACACACATTAGGTACACACCGAACACACACAACACACATTAAATGCCACATACAACACACCACACACATTAAACACACACCCCACACATAAGTCACACACATCACACACACAACACACCATGCGCTAAATACATCACACATACTACACACATGCAAATCACATCACAGACACCACATACGCACCACACCACATACCACACACACGACACATCACATGCCACACATCACCTGTCACACACATCAAACACACACACAATACACCACACACCTCACACACGTCAAACAAACCCCACACACACCATATCACACACACATCACACACACCACACATGCACCATAT | tr-solve-v0.2.0-linux_x86_64
thread 'main' panicked at 'explicit panic', src/hmm.rs:262:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by egor-dolzhenko** [comment] 2023-09-28 13:19
Thanks! I will take a look at this today

**Comment by egor-dolzhenko** [comment] 2023-09-29 02:00
Just got around to testing this and realized that the issue is caused by `N`s. Should we close this issue since it is a special case of issue #4?

**Comment by hdashnow** [comment] 2023-09-29 02:34
Oops, sorry. I assumed since the message was different it was something else. I missed the Ns. Yes, will close this

**Closed as completed** 2023-09-29 02:34 UTC
